/* SQL_Initial_Assessment */
SELECT
    name AS ConfigName,
    value AS ConfigValue,
    value_in_use AS ValueInUse,
    minimum AS MinimumValue,
    maximum AS MaximumValue,
    description AS Description,
    is_dynamic AS IsDynamic,
    is_advanced AS IsAdvanced
FROM sys.configurations
WHERE name IN (
    'max degree of parallelism',
    'cost threshold for parallelism',
    'max server memory (MB)',
    'min server memory (MB)',
    'optimize for ad hoc workloads',
    'backup compression default',
    'remote admin connections',
    'clr enabled',
    'clr strict security',
    'xp_cmdshell',
    'Ole Automation Procedures',
    'cross db ownership chaining',
    'Database Mail XPs',
    'Ad Hoc Distributed Queries',
    'remote access',
    'remote login timeout (s)',
    'remote query timeout (s)',
    'blocked process threshold (s)',
    'fill factor (%)',
    'backup checksum default',
    'contained database authentication',
    'lightweight pooling',
    'priority boost',
    'affinity mask',
    'affinity I/O mask',
    'network packet size (B)',
    'user connections',
    'user options',
    'default language',
    'default full-text language',
    'max text repl size (B)',
    'Agent XPs',
    'scan for startup procs',
    'PH timeout (s)',
    'nested triggers',
    'server trigger recursion',
    'transform noise words',
    'two digit year cutoff',
    'index create memory (KB)',
    'min memory per query (KB)',
    'query wait (s)',
    'recovery interval (min)',
    'locks'
)
ORDER BY name;
