/* SQL_Initial_Assessment */
SELECT
    DB_NAME() AS DatabaseName,
    (SELECT COUNT(*) FROM sys.tables WHERE is_ms_shipped = 0) AS UserTableCount,
    (SELECT COUNT(*) FROM sys.views WHERE is_ms_shipped = 0) AS UserViewCount,
    (SELECT COUNT(*) FROM sys.procedures WHERE is_ms_shipped = 0) AS StoredProcedureCount,
    (SELECT COUNT(*) FROM sys.objects WHERE type = 'FN' AND is_ms_shipped = 0) AS ScalarFunctionCount,
    (SELECT COUNT(*) FROM sys.objects WHERE type = 'IF' AND is_ms_shipped = 0) AS InlineTvfCount,
    (SELECT COUNT(*) FROM sys.objects WHERE type = 'TF' AND is_ms_shipped = 0) AS MultiStatementTvfCount,
    (SELECT COUNT(*) FROM sys.triggers WHERE parent_class = 1 AND is_ms_shipped = 0) AS DmlTriggerCount,
    (SELECT COUNT(*) FROM sys.triggers WHERE parent_class = 0 AND is_ms_shipped = 0) AS DatabaseTriggerCount,
    (SELECT COUNT(*) FROM sys.synonyms) AS SynonymCount,
    (SELECT COUNT(*) FROM sys.sequences) AS SequenceCount,
    (SELECT COUNT(*) FROM sys.types WHERE is_user_defined = 1) AS UserDefinedTypeCount,
    (SELECT COUNT(*) FROM sys.xml_schema_collections WHERE xml_collection_id > 1) AS XmlSchemaCollectionCount,
    (SELECT COUNT(*) FROM sys.fulltext_catalogs) AS FullTextCatalogCount,
    (SELECT COUNT(*) FROM sys.partition_schemes) AS PartitionSchemeCount,
    (SELECT COUNT(*) FROM sys.filegroups WHERE type = 'FG') AS FilegroupCount,
    (SELECT COUNT(*) FROM sys.schemas WHERE schema_id > 4 AND name NOT IN ('db_owner','db_accessadmin','db_securityadmin','db_ddladmin','db_backupoperator','db_datareader','db_datawriter','db_denydatareader','db_denydatawriter','guest','INFORMATION_SCHEMA','sys')) AS UserSchemaCount,
    (SELECT COUNT(*) FROM sys.tables t WHERE t.temporal_type > 0 AND t.is_ms_shipped = 0) AS TemporalTableCount,
    (SELECT COUNT(*) FROM sys.tables t WHERE t.is_memory_optimized = 1 AND t.is_ms_shipped = 0) AS MemoryOptimizedTableCount,
    (SELECT COUNT(*) FROM sys.tables t WHERE t.is_filetable = 1) AS FileTableCount,
    (SELECT COUNT(*) FROM sys.columns c INNER JOIN sys.tables t ON c.object_id = t.object_id WHERE t.is_ms_shipped = 0 AND c.is_filestream = 1) AS FilestreamColumnCount,
    (SELECT COUNT(*) FROM sys.columns c INNER JOIN sys.tables t ON c.object_id = t.object_id WHERE t.is_ms_shipped = 0 AND c.system_type_id = 241) AS XmlColumnCount,
    (SELECT COUNT(*) FROM sys.columns c INNER JOIN sys.tables t ON c.object_id = t.object_id INNER JOIN sys.types ty ON c.user_type_id = ty.user_type_id WHERE t.is_ms_shipped = 0 AND ty.name IN ('geography','geometry','hierarchyid')) AS SpatialOrHierarchyColumnCount;
